### ISSUE TITLE
Produce schema-conformant Results

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-sympy-provider#40]
From #33

At the moment, the simulators build a `dict` for the results, that is finally converted to a real Result using a helper function:
```python
        result = {'backend': self.name,
                  'id': qobj.qobj_id,
                  ...,
                  'time_taken': (end - start)}
        return result_from_old_style_dict(
            result,
            [circuit.header.name for circuit in qobj.experiments])
```

They should be updated so they build the results in conformance to the result specification, so the helper function is not used. I think there are two approaches:
* build each individual element directly (similar to [the helper function internals](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/result/_utils.py#L18)) in each step.
* keep building the dict, but make sure it conforms to the specs, and finally convert it into a Result object.

Pinging @jaygambetta to check if it is acceptable that `qiskit.qobj.blah` elements are imported (might be related to another issue in the terra repo).

**Comment by jaygambetta** [comment]
I am fine that they are imported but this is why we need to finalize our policy moving forward in terra so that not too many things that depend on backends need to be updated.
